### PR TITLE
Fix manifest removal for mac

### PR DESCRIPTION
**Pull request by TCourtneyOwen**
The manifest was not getting properly removed on Mac when calling office-tool remove as follows:

office-toolbox remove -m <project_manifest_path> -a <host>

It wasn't getting removed because we were using the project_manifest_path in removeManifestFromSideloadingDirectory rather than the sideloadingManifestPath where the manifest is cached

### CODE REVIEW

**Review by akrantz — DISMISSED** [review]

**Review by akrantz — COMMENTED** [review]
This makes it so it just uses the base filename when removing a manifest. Really it should remove the manifest based on the manifest add-in id. The file could be for a different manifest, but it would remove it so long as the filename matches.

Also, don't you still need to handle showing an error when adding a manifest and a file with that filename already exists?

**Comment by TCourtneyOwen** [comment]
I can include the changes to make the file name included in the guid in this PR, but had intended to do it in a separate PR. Not sure how the guid in the manifest name will impact removal changes

**Comment by akrantz** [comment]
Well, let's go ahead and make this change. Once we have the additional change to put the guid in the manifest, we can evaluate and make any fixes required before publishing an update.

**Review by akrantz — APPROVED** [review]

**Comment by TCourtneyOwen** [comment]
I pretty much have the change for adding a guid-named named manifest to the Mac wef completed

**Pull request merged**
